baseURL = 'https://nebell.github.io/'
languageCode = 'zh-cn'
hasCJDLanguage = true
title = "Nebell's BLOG"
disqusShortname = "NEBELL"
contentdir = "content"
layoutdir = "layouts"
publishdir = "public"
builddrafts = false
canonifyurls = true
enableEmoji = true
toc = true


hjsStyle = "default"

theme = "casper"

[params]
    description = "人生如逆旅，我亦是行人。"
    logo = "https://avatars.githubusercontent.com/nebell"
    cover = "https://i.loli.net/2021/11/03/bv3TZKilkE8HuNz.jpg"
    author = "Nebell"
    hideHUGOSupport = true
    share = false

[permalinks]
    post = "/:year/:month/:title"

[[menu.main]]
    name = "Github"
    pre = "<h5>链接🔗</h5>"
    url = "https://github.com/Nebell"
    weight = 110
[[menu.main]]
    name = "Gitee"
    url = "https://gitee.com/Nebell"
    weight = 109
[[menu.main]]
    name = "文章"
    url = "/posts/"
    weight = 108

